apis/axios.ts, apis/chatListAPI.ts, pages/all-chat-list/index.tsx, pages/my-chat-list/index.tsx
채팅방 목록 페이지
전체 채팅 목록 url: /all-chat-list
나의 채팅 목록 url: /my-chat-list
디자인없이 단순 목록 조회만 가능하도록 구현했습니다.
=> Feat: 채팅방 목록 조회 기능 구현

styles/_mixin.scss, styles/_variables.scss, styles/index.scss, styles/normalize.scss
- styles/_mixin.scss
- styles/_variables.scss
- styles/index.scss
- styles/normalize.scss
공통 styles 파일 수정 및 추가
- Talkhaja\styles\_mixin.scss
- 상단 @use './variables' as *; 제거    -
- @mixin container 추가
- styles\normalize.scss
- html{font-size: 62.5%; } 추가 
(html 기본 폰트 사이즈 기존 16px에서 10px로 변경하였습니다. 10px = 1rem)
- a{text-decoration: none;  color: #000;  cursor: pointer;} 추가
- ul list-style, margin, padding 제거
- styles\_variables.scss
- 변수명 변경, 추가
- styles\index.scss 파일 생성
- 각 파일명.module.scss 상단에 @import '@/styles/index.scss'; 하시면 mixin, variables에 있는 변수들 사용 가능합니다.
- next.js 에서는 @use './variables' as *; 방식으로 import가 불가한 것 같습니다. import 방식에 대해 조금 더 찾아봐야 할 것 같습니다.
=> TALK-22--feat/layout/styles 공통 styles 파일 수정 및 추가

components/Navigation/Navigation.module.scss, components/Navigation/Navigation.tsx, package-lock.json, package.json, pages/_app.tsx
- components/Navigation/Navigation.module.scss
- components/Navigation/Navigation.tsx
- package-lock.json
- package.json
- pages/_app.tsx
- 하단 내비게이션 바
- react-icons 설치하였습니다. npm i 부탁드립니다.
- Bootstrap Icons 사용하였습니다.
```
import { IconName } from "react-icons/bs"; 
```
=> TALK-20--feat/layout/nav 하단 내비게이션 바 추가

package-lock.json, package.json, utils/firebaseConfig.ts
- package-lock.json
- package.json
- utils/firebaseConfig.ts
- firebase 설치
- firebaseConfig 파일 생성
npm i 부탁드립니다.
.env파일 내용 따로 전달드리겠습니다!
=> TALK-21--feat/user/hostList firebase 설치 및 firebaseConfig 파일 생성

components/chat/header.tsx, pages/chat/index.tsx
채팅방 페이지
채팅방 내에서 모달 버튼 나가기 기능 구현했습니다.
현재 나가면 home 화면으로 되돌아갑니다 -> 채팅방 목록으로 나가는 걸로 수정해야 합니다.
=> feat : 채팅방 나가기 기능 구현

components/Navigation/Navigation.module.scss
- 하단 내비게이션 
- components/Navigation/Navigation.module.scss
기존 아이콘과 텍스트에 호버 효과가 각각 적용되는 문제 수정.
단순 디자인만 수정하였습니다.
=> Talk 20  feat/layout/nav 하단 네비게이션 호버 효과 수정

apis/chatListAPI.ts, components/ChatList/CreateChat.tsx, pages/chat-list/ChatList.module.scss, pages/chat-list/all.tsx, pages/chat-list/my.tsx
채팅방 목록 페이지
채팅방 생성 기능 구현
채팅방 참여 기능 구현
1. 상단 왼쪽에 + 버튼을 클릭하고 채팅방 이름을 입력하면 채팅방 생성이 가능합니다.
2. 현재 채팅방 참여 여부는 'user3'를 기준으로 되어있습니다.
3. 디자인은 임시 적용 상태입니다.
4. 만약에 자신이 테스트하는 계정으로 채팅 참여 여부를 구분하고 싶다면 `Talkhaja/pages/chat-list/all.tsx`에 31번줄 `user3`를 자신이 테스트하는 계정 id로 변경하면 됩니다.
5. 준혁님께서 recoil에 로그인 유저 정보 저장이 안료되면 수정하겠습니다
오른쪽 상단 채팅방 생성 버튼
=> Feat: 채팅방 생성, 참여 기능 구현

@types/types.ts, components/host-list/HostDetailsModal.tsx, pages/chat-list/ChatList.module.scss, pages/chat-list/all.tsx, pages/chat-list/my.tsx
숙소 목록 페이지
채팅 목록 페이지
숙소 문의 채팅 기능 구현
나의 채팅 목록에 숙소와 채팅과 유저와 채팅 구분
=> Feat: 숙소와 채팅 기능 구현

apis/chatListAPI.ts, pages/chat-list/all.tsx, utils/loginStorage.ts
채팅 목록 페이지
- instance Jwtinterceptors로 수정
- 로컬 스토리지 저장 방식 수정
=> Talk 4  feat/chat list

apis/Jwtinterceptors.ts, components/Navigation/Navigation.tsx, components/signup/SignUpModal.tsx, pages/login/index.tsx, pages/login/login.module.scss, pages/mypage/index.tsx, pages/signup/index.tsx
1. 로그인 페이지
2. 회원가입 페이지
3. JwtInterceptor
1. 로그인 회원가입 로직 수정(불필요한 state삭제)
2. 회원가입 이미지 에러 해결
3. JwtInterceptor 로직 수정 및 config 에러 해결
=> Fix: 회원가입, Jwt 토큰 에러 수정

components/ChatList/CreateChat.tsx, components/host-list/HostDetailsModal.tsx, pages/chat-list/all.tsx
숙소 목록 페이지
이미 채팅방이 생성되어 있는 숙소는 '문의하기' 하기 눌러도 생성되지 않고 이미 존재하는 채팅방으로 이동
=> Refactor: 숙소와 채팅이 존재하면 미생성 후 이동

pages/chat/[chatId].tsx
=> fix : 쓸모없는 코드 삭제

components/ChatList/ChatListModal.module.scss, components/ChatList/ChatListModal.tsx, components/ChatList/MyChatListItem.tsx, pages/chat-list/ChatList.module.scss, pages/chat-list/all.tsx, pages/chat-list/my.tsx
=> Talk 65  etc/chat list

components/ChatList/ChatListModal.module.scss, components/ChatList/ChatListModal.tsx, components/ChatList/MyChatListItem.tsx, pages/chat-list/ChatList.module.scss, pages/chat-list/all.tsx, pages/chat-list/my.tsx
채팅방 목록 페이지
채팅방 이름 제한걸어놨습니다
채팅방 목록 페이지 디자인 변경하였습니다
나의 채팅방 목록 부분 리스트 컴포넌트 분리하였습니다.
=> refactor : 채팅방 목록

apis/socket.ts, hooks/useConnectServerSocket.tsx, pages/chat-list/all.tsx, pages/chat-list/my.tsx, utils/chatList.ts, utils/formattedTimeData.ts
=> Talk 9  feat/chat list/get list

pages/_app.tsx
Expectation Violation: Duplicate atom key "userIdState". This is a FATAL ERROR in
production. But it is safe to ignore this warning if it occurred because of
hot module replacement.
at expectationViolation 
해당 에러에 대한 오류 해결하였습니다.
env파일에 아래 코드 추가해주세요
RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=false
https://jaylee-log.tistory.com/102
=> fix : recoil atom 중복 에러 해결

pages/chat-list/all.tsx
=> Style: console.log 제거

components/Header/Header.module.scss, components/Header/Header.tsx, pages/chat-list/ChatList.module.scss, pages/chat-list/all.tsx, pages/chat-list/my.tsx, pages/host-list/hostList.module.scss, pages/index.tsx
=> Talk 38  etc/header

components/ChatList/MyChatListItem.tsx, pages/chat-list/my.tsx
=> Fix: conflict error 해결

pages/chat-list/ChatList.module.scss, pages/chat-list/all.tsx, styles/_mixin.scss, styles/_variables.scss, utils/timeFormat.ts
오픈 채팅 목록 
- 오픈 채팅 목록 시간 표시 세분화
- 시간 표시 위치 변경
=> Talk 11  feat/chat list/chat time 오픈 채팅 목록 타임포맷팅 / 표시 위치 변경

components/HostList/hostList.module.scss
=> Design: 홈 상단 여백 추가

components/HostList/HostDetailsModal.tsx
=> Fix: 숙소 채팅 생성 오류 수정

components/HostList/HostDetailsModal.tsx, components/HostList/hostList.module.scss, pages/chat-list/ChatList.module.scss, utils/timeFormat.ts
=> Talk 10  feat/chat list/create

components/ChatList/MyChatListItem.tsx, pages/chat-list/ChatList.module.scss, pages/chat-list/all.tsx, styles/normalize.scss
=> design: 채팅방 hover 스타일 추가

@types/types.ts, components/chat/mychat.tsx, components/chat/otherchat.tsx, pages/chat/[chatId].tsx
chat 페이지
1. 타입 에러 해결
2. Join 유저 API 변동으로 인한 코드, 타입 변경
3. 채팅방 출입유저 메세지 오류 수정
=> Talk 18  feat/chat/view join

components/HostList/HostDetailsModal.tsx, components/HostList/HostListItem.tsx
=> Fix: 에러 해결

components/chat/Chat.module.scss
=> 채팅방 Height값 관련 이슈 해결

components/HostList/HostDetailsModal.module.scss, components/HostList/HostDetailsModal.tsx, pages/host-list/index.tsx
숙소 목록 모달 페이지
- 이미지 태그 백그라운드 이미지로 변경
- 모바일 환경에서 헤더와 모달 영역  겹쳐지는 현상으로 모달 컴포넌트 섹션 영역 바깥으로 이동했습니다.
- 모달 사이즈 변경 하였습니다. 
- 모달 이미지 <IMAGE />태그에서 backgroundImage로 변경하였습니다.
- pc
- mo
=> Design: 숙소 모달 IMAGE태그 backgroundImage로 변경

components/HostList/HostDetailsModal.module.scss
숙소 목록 상세 모달
fontsize 수정
기존 폰트 너무 작아서 $font-size-base로 변경했습니다.
=> Chore: 모달 font-size 수정
